{
 "title": "CPU Usages",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Single Threaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"datastore_single_threaded\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Threaded CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"datastore_multithreaded\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Single Threaded Event Driven",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"datastore_single_threaded_epoll\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}