{
 "title": "CPU Usage",
 "time": { "from": "2025-11-30T05:49:22.615Z", "to": "2025-11-30T06:49:22.615Z" },
 "panels": [
  {
   "title": "Single threaded Epoll CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"datastore_single_threaded_epoll\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "Single Threaded Epoll Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{name=\"datastore_single_threaded_epoll\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "Multi Threaded CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"datastore_multithreaded\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "Multi Threaded Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{name=\"datastore_multithreaded\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "Single Threaded CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"datastore_single_threaded\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "Single Threaded Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{name=\"datastore_single_threaded\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  }
 ]
}