{
 "title": "CPU Usage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"datastore_single_threaded_epoll\"}[$__rate_interval]))",
     "legendFormat": "epoll"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"datastore_multithreaded\"}[$__rate_interval]))",
     "legendFormat": "multi thread"
    }
   ]
  },
  {
   "title": "Memory Usages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{name=\"datastore_single_threaded_epoll\"})",
     "legendFormat": "epoll"
    },
    {
     "expr": "avg(container_memory_usage_bytes{name=\"datastore_multithreaded\"})",
     "legendFormat": "multi thread"
    }
   ]
  },
  {
   "title": "Received Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"datastore_single_threaded_epoll\"}[$__rate_interval]))",
     "legendFormat": "epoll"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"datastore_multithreaded\"}[$__rate_interval]))",
     "legendFormat": "multi threaded"
    }
   ]
  },
  {
   "title": "Dropped Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{name=\"datastore_single_threaded_epoll\"}[$__rate_interval]))",
     "legendFormat": "epoll"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{name=\"datastore_multithreaded\"}[$__rate_interval]))",
     "legendFormat": "multi threaded"
    }
   ]
  }
 ]
}