# Use a minimal Python image
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /app

RUN apt update && apt install htop procps -y

# Copy the server code into the container
COPY server.py .

# Expose the TCP port
EXPOSE 3001

# Command to run the server
CMD ["python3", "-u","server.py"]
